name: Prettier Check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install Prettier and Plugins
        run: npm install --no-save prettier prettier-plugin-tailwindcss

      - name: Run Prettier check
        id: prettier
        continue-on-error: true
        run: npx prettier --check "**/*.{js,ts,jsx,tsx,html,css,scss,json}"

      - name: Comment on PR if Prettier fails
        if: steps.prettier.outcome == 'failure'
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Prettier check failed 🌩. Run `npm run format`. \
                     Check all is good `npm run check` and \
                     re-commit the code."
            })

      - name: Fail the job if Prettier failed
        if: steps.prettier.outcome == 'failure'
        run: exit 1
